services:
  postgres:
    container_name: postgres-rtm
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: rust_team_manager
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - spring-rtm

  keycloak:
    container_name: keycloak-rtm
    image: quay.io/keycloak/keycloak:26.2.1
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - spring-rtm
    command:
      - "start-dev"

networks:
  spring-rtm:
    driver: bridge

volumes:
  postgres:
    driver: local
  keycloak:
    driver: local