spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rust_team_manager
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/ruest-team-manager"
          audiences: rtm
server:
  port: 8088
  servlet:
    context-path: /api/v1/
springdoc:
  default-produces-media-type: application/json


